export const ADD_SERVICE = 'ADD_SERVICE';
export const FETCH_SERVICE = 'FETCH_SERVICE';
export const SEARCH_SERVICE = 'SEARCH_SERVICE';
export const FILTER_SERVICE = 'FILTER_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const FIND_SERVICE_BY_SERVICEID = 'FIND_SERVICE_BY_SERVICEID';


export const SAVE_SERVICE_CODE = 'SAVE_SERVICE_CODE'; 

export const FETCH_SERVICE_FILTER = 'FETCH_SERVICE_FILTER';
export const TOTAL_SERVICE = 'TOTAL_SERVICE';
export const FETCH_SERVICE_ALL = 'FETCH_SERVICE_ALL';

export const IS_FETCHING_SERVICE = 'IS_FETCHING_SERVICE';
export const FILTER_SERVICE_ORGAN = 'FILTER_SERVICE_ORGAN';

export const SET_SCOPE = 'SET_SCOPE';